version: "3.5"
services:
  app:
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    #  volumes:
    #    - ./data:/data/db
    ports:
      - "27017:27017"
